---
collections:
  # Install a collection from Ansible Galaxy.
  - name: ansible.windows
    version: 1.11.0
  - name: community.general
  - name: community.windows
    version: 1.11.0
  - name: chocolatey.chocolatey
  - name: microsoft.ad
# - name: goad.windows
#   type: dir
#   source: ./collections/goad/windows
